-   id: ess
    name: ess - env sample sync
    description: Automatically and safely synchronize .env files with env.sample
    language: golang
    entry: ess
    always_run: true
    pass_filenames: false
    stages: [commit]
