-   id: env-sample-sync
    name: env-sample-sync env sample file synchronizer
    description: Automatically and safely synchronize .env files with env.sample
    language: golang
    entry: env-sample-sync
    always_run: true
    pass_filenames: false
    stages: [commit]
